### ISSUE TITLE
:art:Project Repo Link

### ISSUE THREAD

**Issue by nejidevelops** [hetrox8/Movie_App#21]
Here is our [project link](https://github.com/hetrox8/Javascript-Capstone/projects/1)

**The team is of two: @hetrox8  and @NewtonOmbese**

**Comment by binhussen** [comment]
@NewtonOmbese and @NewtonOmbese would update the project link to this https://github.com/hetrox8/Javascript-Capstone/projects/1

**Comment by nejidevelops** [comment]
@binhussen  kindly clarify I don't get what you mean here kindly

**Comment by binhussen** [comment]
this link has to be to the kanban board project https://github.com/hetrox8/Javascript-Capstone/projects/1
![Uploading 2023-08-01_12-22.png…]()

**Comment by nejidevelops** [comment]
@binhussen I have fixed that

**Comment by binhussen** [comment]
Hi @NewtonOmbese and @hetrox8 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights

- Used [Given Template](https://github.com/microverseinc/curriculum-javascript/projects/1)✔️
- Failrly Distributed Task ✔️
- Descriptive Issue ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by binhussen** [comment]
@NewtonOmbese delete the above commnets
<img width="503" alt="2023-08-01_12-26" src="https://github.com/hetrox8/Javascript-Capstone/assets/52010789/01448f0d-44c7-4a08-ad7f-3dad2c783304">
